services:
  minio:
    image: quay.io/minio/minio
    container_name: minio1
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - ${HOME}/minio/data:/data
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    command: server /data --console-address ":9001"
    networks:
      - mlflow_network

  minio_mc:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./setup_minio.sh:/setup_minio.sh  # Mount setup script
    entrypoint: /bin/sh -c "/setup_minio.sh"
    networks:
      - mlflow_network

networks:
  mlflow_network:
    driver: bridge
